x-uffizzi:
  ingress:
    service: app
    port: 80

services:
  app:
    build:
      context: https://github.com/ITZ-ZAID/Telethon-Music
      dockerfile: Dockerfile
    environment:
      NODE_ENV: staging
    deploy:
      resources:
        limits:
          memory: 2500M
    restart: always
    ports:
      - "3000:3000"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
    restart: always
volumes:
  data:
